global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "sre_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'sre-cicd-demo'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']
    metrics_path: /metrics
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
