# ElastAlert Configuration for Log-based Alerting

# ElastAlert required settings
rules_folder: /opt/elastalert/rules
run_every:
  minutes: 1

buffer_time:
  minutes: 15

# Elasticsearch connection
es_host: elasticsearch
es_port: 9200
es_username: 
es_password:

# Optional: Authentication
# es_username: elastic
# es_password: changeme

# SSL settings (if enabled)
# use_ssl: True
# verify_certs: True

# Index settings
writeback_index: elastalert_status
writeback_alias: elastalert_alerts

# Alert settings
alert_time_limit:
  days: 2

# Email settings (configure as needed)
smtp_host: ${SMTP_HOST}
smtp_port: ${SMTP_PORT:587}
smtp_auth_file: /opt/elastalert/smtp_auth.yaml
from_addr: alerts@company.com

# Slack settings
slack_webhook_url: ${SLACK_WEBHOOK_URL}
slack_channel_override: "#alerts"
slack_username_override: "ElastAlert"
slack_emoji_override: ":warning:"

# Global alert settings
max_query_size: 100000
max_aggregation: 10000
scroll_keepalive: 30s

# Logging
logging:
  version: 1
  incremental: false
  disable_existing_loggers: false
  formatters:
    logline:
      format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: logline
      level: INFO
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: logline
      filename: /opt/elastalert/logs/elastalert.log
      maxBytes: 10485760
      backupCount: 5
      level: INFO
  loggers:
    elastalert:
      level: INFO
      handlers: [console, file]
      propagate: false
  root:
    level: INFO
    handlers: [console]
