# Filebeat Configuration for Log Collection

# ======================= Filebeat inputs =============================

filebeat.inputs:

# Application logs
- type: log
  id: application-logs
  enabled: true
  paths:
    - /var/log/app/*.log
    - /app/logs/*.log
  fields:
    service: webapp
    environment: ${ENVIRONMENT:development}
    log_type: application
  fields_under_root: true
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  scan_frequency: 10s
  harvester_buffer_size: 16384
  max_bytes: 10485760

# Container logs
- type: container
  id: docker-logs
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'
  fields:
    log_type: container
    source_type: docker
  fields_under_root: true
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - decode_json_fields:
        fields: ["message"]
        target: "parsed"
        overwrite_keys: true
        add_error_key: true

# System logs
- type: log
  id: system-logs
  enabled: true
  paths:
    - /var/log/syslog
    - /var/log/auth.log
    - /var/log/kern.log
  fields:
    log_type: system
    source_type: syslog
  fields_under_root: true

# Nginx access logs
- type: log
  id: nginx-access
  enabled: true
  paths:
    - /var/log/nginx/access.log
  fields:
    log_type: nginx_access
    service: nginx
  fields_under_root: true

# Nginx error logs  
- type: log
  id: nginx-error
  enabled: true
  paths:
    - /var/log/nginx/error.log
  fields:
    log_type: nginx_error
    service: nginx
  fields_under_root: true
  multiline.pattern: '^\d{4}/\d{2}/\d{2}'
  multiline.negate: true
  multiline.match: after

# Security logs
- type: log
  id: security-logs
  enabled: true
  paths:
    - /var/log/secure
    - /var/log/audit/audit.log
  fields:
    log_type: security
    security_category: audit
  fields_under_root: true

# Journal logs (systemd)
- type: journald
  id: journald-logs
  enabled: true
  fields:
    log_type: journal
    source_type: systemd
  fields_under_root: true

# ======================= Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Processors ===================================

processors:
  # Add hostname and IP address
  - add_host_metadata:
      when.not.contains.tags: forwarded
      
  # Add Docker metadata
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      
  # Add Kubernetes metadata
  - add_kubernetes_metadata:
      host: ${NODE_NAME}
      matchers:
      - logs_path:
          logs_path: "/var/log/containers/"

  # Drop empty events
  - drop_event:
      when:
        equals:
          message: ""

  # Add environment tags
  - add_tags:
      tags: [logs, filebeat]
      target: tags

  # Rename fields for consistency
  - rename:
      fields:
        - from: "host.name"
          to: "hostname"

# ======================= Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  _source.enabled: true

# Index lifecycle management
setup.ilm.enabled: true
setup.ilm.rollover_alias: "logs"
setup.ilm.pattern: "logs-*"
setup.ilm.policy: "logs-policy"

# ======================= Kibana dashboards ==============================

setup.dashboards.enabled: true
setup.dashboards.index: ".kibana"

# ======================= Outputs =============================

# Elasticsearch output (commented out - using Logstash)
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "logs-%{+yyyy.MM.dd}"

# Logstash output
output.logstash:
  hosts: ["logstash:5044"]
  compression_level: 3
  bulk_max_size: 2048
  template.name: "logs"
  template.pattern: "logs-*"

# ======================= Logging =============================

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644

# ======================= Monitoring =============================

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]

# ======================= HTTP endpoint =============================

http.enabled: true
http.host: 0.0.0.0
http.port: 5066

# ======================= Performance tuning =============================

queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 5s

# File harvesting settings
filebeat.registry.flush: 5s
