global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@company.com'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        slo: 'error_rate'
      receiver: 'slo-violations'
    - match:
        slo: 'latency'
      receiver: 'slo-violations'
    - match:
        slo: 'availability'
      receiver: 'slo-violations'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@company.com'
        subject: 'Critical Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    
    webhook_configs:
      - url: 'http://localhost:5001/critical'
        send_resolved: true

  - name: 'slo-violations'
    email_configs:
      - to: 'sre-team@company.com'
        subject: 'SLO Violation: {{ .CommonLabels.slo }}'
        body: |
          SLO Violation Detected!
          
          SLO: {{ .CommonLabels.slo }}
          {{ range .Alerts }}
          Alert: {{ .Labels.alertname }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
