name: Pipeline Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  basic-test:
    name: Basic Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Basic Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Test Python Setup
      run: |
        python --version
        pip --version
        echo "✅ Python environment ready"
    
    - name: Simple Test
      run: |
        echo "Testing basic functionality..."
        python -c "print('Hello from SRE Pipeline!')"
        echo "✅ Basic test passed"
    
    - name: Check Repository Structure
      run: |
        echo "Repository contents:"
        ls -la
        echo "✅ Repository structure verified"
    
    - name: Test Status
      run: |
        echo "🎉 Basic pipeline test completed successfully!"
        echo "This confirms GitHub Actions can run our code"
